// searchData.js
// A clean, separated database of my website's content

const siteDirectory = [
  {
    title: "Treaty 1 Overview & Foundation",
    keywords: [
      "home",
      "overview",
      "intro",
      "winnipeg treaty",
      "foundation",
      "education",
      "start",
    ],
    url: "index.html#main-content",
  },
  {
    title: "The Gathering at Lower Fort Garry",
    keywords: [
      "lower fort garry",
      "history",
      "negotiation",
      "1871",
      "treaty",
      "stone fort",
      "gathering",
    ],
    url: "negotiation.html#at-the-table",
  },
  {
    title: "Chief Mis-koo-kenew (Red Eagle)",
    keywords: [
      "chief",
      "mis-koo-kenew",
      "red eagle",
      "leader",
      "anishinaabe",
      "muskego-cree",
      "indigenous",
    ],
    url: "negotiation.html#key-figures",
  },
  {
    title: "Terms & The 'Outside Promises'",
    keywords: [
      "terms",
      "outside promises",
      "160 acres",
      "ploughs",
      "livestock",
      "oxen",
      "cows",
      "clothing",
      "verbal agreements",
    ],
    url: "negotiation.html#outside-promises",
  },
  {
    title: "Treaty 1 Territory & Maps",
    keywords: [
      "map",
      "maps",
      "geography",
      "borders",
      "territory",
      "where",
      "size",
      "16,700 square miles",
      "provincial context",
    ],
    url: "index.html#geography",
  },
  {
    title: "Participating First Nations",
    keywords: [
      "peguis",
      "brokenhead",
      "long plain",
      "roseau river",
      "sagkeeng",
      "sandy bay",
      "swan lake",
      "communities",
      "nations",
      "bands",
      "seven",
      "st. peter's",
      "fort alexander",
    ],
    url: "index.html#first-nations",
  },
  {
    title: "Naawi-Oodena & Kapyong Barracks",
    keywords: [
      "kapyong",
      "modern",
      "urban reserve",
      "naawi-oodena",
      "barracks",
      "redevelopment",
      "city",
      "winnipeg",
    ],
    url: "modern.html#naawi-oodena",
  },
  {
    title: "Economic Sovereignty",
    keywords: [
      "economic",
      "sovereignty",
      "development zones",
      "trade",
      "modern economy",
      "business",
      "money",
    ],
    url: "modern.html#economic-sovereignty",
  },
  {
    title: "History Knowledge Quiz",
    keywords: [
      "quiz",
      "test",
      "knowledge",
      "history test",
      "exam",
      "questions",
    ],
    url: "negotiation.html#history-quiz",
  },
  {
    title: "Modern Implementation Quiz",
    keywords: [
      "quiz",
      "test",
      "knowledge",
      "modern test",
      "exam",
      "implementation",
    ],
    url: "modern.html#modern-quiz",
  },
];
